### ISSUE TITLE
error not working for me

### ISSUE THREAD

**Issue by yusifdhrgam12** [mraffaele/Steam-Regional-Price-Checker#1]
i used all your instruction and get me this error when i run node server.js 
this mess shown in port 3000
{"error":"404: Page Not Found"}

**Comment by mraffaele-carsales** [comment]
Hi, this is actually expected at the API doesn't have a route for `/`, but you bring up a good point in that it does make it look broken. I will create a route for the homepage to show that it is working.

You can test its working by hitting an endpoint such as http://localhost:3000/2.0/get/app/678950/

**Comment by mraffaele-carsales** [comment]
hey @yusifdhrgam12 I've just made commit which creates a route for `/`. If you checkout the latest you should be good to go.

**Comment by mraffaele** [comment]
Hi @yusifdhrgam12 this is actually expected at the API doesn't have a route for /, but you bring up a good point in that it does make it look broken. I've just made commit which creates a route for `/`. If you checkout the latest you should be good to go,

You can otherwise test its working by hitting an endpoint such as http://localhost:3000/2.0/get/app/678950/

**Comment by yusifdhrgam12** [comment]
thank you worked for me.
